[package]
name = "pythonbrotli"
version = "0.1.0"
authors = ["Mehant Baid <mehant@dropbox.com>", "Daniel Reiter Horn <danielrh@dropbox.com>"]

[dependencies]
libc = "0.2.5"
brotli = {git = "https://github.com/dropbox/brotli-rs.git"}

[lib]
name = "pythonbrotli"
crate-type = ["dylib"]
