[package]
name = "embed"
version = "0.1.0"
authors = ["Mehant Baid <mehant@dropbox.com>"]

[dependencies]
libc = "0.2.5"
brotli = {git = "https://github.com/ende76/brotli-rs.git"} 
[lib]
name = "embed"
crate-type = ["dylib"]
